APP:
  ENVIRONMENT: test
  DEBUG: True
  # Only accept True or False

DATABASE:
  USERNAME: demo
  PASSWORD: Demo123!
  CONNECTIONS:
    db1:
      host: cassandra-pods
      port: 9042
    db2:
      host: 127.0.0.1
      port: 9052
