apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2022-11-02T12:02:20Z"
  labels:
    app: transaction-service
    app.kubernetes.io/component: transaction-service
    app.kubernetes.io/instance: transaction-service
  name: transaction-service
  namespace: res-demo
  resourceVersion: "20409552"
  uid: 6d92b884-7948-4d78-b21e-cdb3ea708c64
spec:
  clusterIP: 172.21.87.9
  clusterIPs:
  - 172.21.87.9
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 5000-tcp
    port: 5000
    nodePort: 30050  
    protocol: TCP
    targetPort: 5000
  selector:
    deployment: transaction-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
